main_menu:
  - text: "AI4Forest"
    url: "/"
    menu_type: "primary"

  - text: "Researchers"
    url: "/researchers"
    menu_type: "primary"

  - text: "Publications"
    url: "/publications"
    menu_type: "primary"